# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9677de168141037ce7931e57759449ffd9a9ae8081f7563678b740c6deb846c0ec4ee934be17c32ec74ec0c2a3ad4fa121aa606800198efe9cf3811bcbad431

test:
  secret_key_base: 121b3bc3db6a5824c9d64f610c439aea72f4c859f9931b7d3ea1b06096a7ed7257c25cbbf60b3da5b1a270ecf2cf30fbf4dc4c41a6c376031b6d0218c33b4d51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
